name: "Needs more wave"
description: "Adds comment to user's pr"
author: "Turtle"

inputs:
  gh-token:
    description: "The github token for user authorization"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "activity"
  color: "green"
