name: "Waver"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  wave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          user-to-comment-on: ${{ vars.USER_TO_COMMENT_ON }}
          user-gh-token: ${{ secrets.GH_USER_TOKEN }}
