name: "Waver"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  wave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
